# Generated by Django 3.2.12 on 2022-03-11 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accessory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titles', models.CharField(max_length=200)),
                ('prices', models.CharField(max_length=10)),
                ('all_reviews', models.CharField(max_length=30)),
                ('total_reviews', models.CharField(max_length=30)),
            ],
        ),
    ]
